server {
    listen       80;
    listen  [::]:80;
    server_name  ittaspajtatanc.hu;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # redirect server to the custom 404 static page /404.html
    #
    error_page  404              /404.html;
    location = /404.html {
        root   /usr/share/nginx/html;
    }

    # redirect server error pages to the static page /500.html
    #
    error_page   500 502 503 504  /500.html;
    location = /500.html {
        root   /usr/share/nginx/html;
    }
}
